# Generated by Django 5.1.4 on 2024-12-21 18:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField()),
                ('operational_hours', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_identifier', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_location', models.CharField(choices=[('Beji', 'Beji'), ('bojongsari', 'Bojongsari'), ('cilodong', 'Cilodong'), ('cimanggis', 'Cimanggis'), ('cinere', 'Cinere'), ('cipayung', 'Cipayung'), ('limo', 'Limo'), ('pancoran_mas', 'Pancoran Mas'), ('sawangan', 'Sawangan'), ('sukmajaya', 'Sukmajaya'), ('tapos', 'Tapos')], max_length=255)),
                ('preferred_breakfast_type', models.CharField(choices=[('masih_bingung', 'Masih Bingung'), ('nasi', 'Nasi'), ('roti', 'Roti'), ('lontong', 'Lontong'), ('cemilan', 'Cemilan'), ('minuman', 'Minuman'), ('mie', 'Mie'), ('makanan_sehat', 'Sarapan Sehat'), ('bubur', 'Bubur'), ('makanan_berat', 'Sarapan Berat')], max_length=100)),
                ('preferred_price_range', models.CharField(choices=[('0-15000', 'Dibawah Rp 15.000'), ('15000-25000', 'Rp 15.000 - Rp 25.000'), ('25000-50000', 'Rp 25.000 - Rp 50.000'), ('50000-100000', 'Rp 50.000 - Rp 100.000'), ('100000+', 'Diatas Rp 100.000')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
