# Generated by Django 5.1.2 on 2024-10-25 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred_location', models.CharField(choices=[('beji', 'Beji'), ('bojongsari', 'Bojongsari'), ('cilodong', 'Cilodong'), ('cimanggis', 'Cimanggis'), ('cinere', 'Cinere'), ('cipayung', 'Cipayung'), ('limo', 'Limo'), ('pancoran_mas', 'Pancoran Mas'), ('sawangan', 'Sawangan'), ('sukmajaya', 'Sukmajaya'), ('tapos', 'Tapos')], max_length=255)),
                ('preferred_breakfast_type', models.CharField(choices=[('masih_bingung', 'Masih Bingung'), ('nasi', 'Nasi'), ('roti', 'Roti'), ('lontong', 'Lontong'), ('cemilan', 'Cemilan'), ('minuman', 'Minuman')], max_length=100)),
                ('preferred_price_range', models.CharField(choices=[('0-15000', 'Dibawah Rp 15.000'), ('15000-25000', 'Rp 15.000 - Rp 25.000'), ('25000-50000', 'Rp 25.000 - Rp 50.000'), ('50000-100000', 'Rp 50.000 - Rp 100.000'), ('100000+', 'Diatas Rp 100.000')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
