
# Generated by Django 5.1.2 on 2024-10-26 11:23
# Generated by Django 5.1.2 on 2024-10-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_location',
            field=models.CharField(choices=[('Beji', 'Beji'), ('bojongsari', 'Bojongsari'), ('cilodong', 'Cilodong'), ('cimanggis', 'Cimanggis'), ('cinere', 'Cinere'), ('cipayung', 'Cipayung'), ('limo', 'Limo'), ('pancoran_mas', 'Pancoran Mas'), ('sawangan', 'Sawangan'), ('sukmajaya', 'Sukmajaya'), ('tapos', 'Tapos')], max_length=255),
        ),
    ]
