# Generated by Django 5.1.2 on 2024-10-27 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_userpreference_preferred_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='preferred_breakfast_type',
            field=models.CharField(choices=[('masih_bingung', 'Masih Bingung'), ('nasi', 'Nasi'), ('roti', 'Roti'), ('lontong', 'Lontong'), ('cemilan', 'Cemilan'), ('minuman', 'Minuman'), ('mie', 'Mie'), ('sarapan_sehat', 'Sarapan Sehat'), ('bubur', 'Bubur'), ('sarapan_berat', 'Sarapan Berat')], max_length=100),
        ),
    ]
