# Generated by Django 5.1 on 2024-11-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_name_product_food_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_identifier',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
