# Generated by Django 5.1.2 on 2024-10-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resto_name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=4)),
                ('price', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
