# Generated by Django 5.1.2 on 2024-10-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyarap_detailer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailer',
            name='description',
            field=models.TextField(default='No Description Available'),
        ),
        migrations.AddField(
            model_name='detailer',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailer',
            name='price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='detailer',
            name='time',
            field=models.TimeField(),
        ),
    ]
