# Generated by Django 5.1.2 on 2024-10-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyarap_detailer', '0003_alter_detailer_description_alter_detailer_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailer',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
