# Generated by Django 5.1.2 on 2024-10-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyarap_detailer', '0004_alter_detailer_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='detailer',
            name='resto_name',
        ),
        migrations.RemoveField(
            model_name='detailer',
            name='time',
        ),
        migrations.AddField(
            model_name='detailer',
            name='image',
            field=models.URLField(default='no images'),
        ),
        migrations.AddField(
            model_name='detailer',
            name='name',
            field=models.CharField(default='no name', max_length=255),
        ),
        migrations.AddField(
            model_name='detailer',
            name='operational_hours',
            field=models.CharField(default='no name', max_length=100),
        ),
        migrations.AddField(
            model_name='detailer',
            name='restaurant',
            field=models.CharField(default='no name', max_length=255),
        ),
        migrations.AlterField(
            model_name='detailer',
            name='location',
            field=models.CharField(default='no name', max_length=255),
        ),
        migrations.AlterField(
            model_name='detailer',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='detailer',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
