# Generated by Django 4.2.16 on 2024-10-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyarap_nanti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='Default Wishlist', max_length=100),
        ),
    ]
