# Generated by Django 5.1.4 on 2024-12-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyarap_nanti', '0002_remove_wishlistitem_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='wishlist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nyarap_nanti.wishlist'),
            preserve_default=False,
        ),
    ]
