# Generated by Django 4.2.16 on 2024-10-27 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '__first__'),
        ('nyarap_nanti', '0003_remove_wishlist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant'),
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
