# Generated by Django 5.1.4 on 2024-12-20 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nyarap_nanti', '0004_remove_wishlistitem_wishlist_wishlistitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wishlist_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='nyarap_nanti.wishlistitem')),
            ],
        ),
    ]
