# Generated by Django 5.1.4 on 2024-12-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nyarap_nanti', '0005_wishlistnote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionitem',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='collectionitem',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='CollectionItem',
        ),
    ]
